apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: bitcare-attendance
  labels:
    app.kubernetes.io/name: bitcare-attendance-api
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: bitcare-attendance
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bitcare-attendance-api
    app.kubernetes.io/instance: production
  ports:
    - name: http
      port: 80
      targetPort: 8080

