apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: bitcare-attendance
  labels:
    app.kubernetes.io/name: bitcare-attendance-api
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: bitcare-attendance
spec:
  # Headless service: DNS sẽ trả về pod IPs trực tiếp thay vì ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: bitcare-attendance-api
    app.kubernetes.io/instance: production
  ports:
    - name: http
      port: 8080
      targetPort: 8080

