apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: bitcare-attendance
  labels:
    app.kubernetes.io/name: bitcare-attendance-web
    app.kubernetes.io/instance: production
    app.kubernetes.io/part-of: bitcare-attendance
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: bitcare-attendance-web
    app.kubernetes.io/instance: production
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080

