apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitcare-attendance

resources:
  - namespace.yaml
  - db/deployment.yaml
  - db/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: bitcare-attendance
  app.kubernetes.io/instance: production
  app.kubernetes.io/version: "1.0"
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: bitcare-attendance

